import bcrypt from "bcryptjs";

// Hashed password for "password123"
const DEFAULT_HASH = bcrypt.hashSync("password123", 10);

export const INITIAL_USERS = [
  {
    id: "user_1",
    name: "Alex Rivera",
    email: "alex@skillswap.edu",
    passwordHash: DEFAULT_HASH,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    role: "Full-Stack Engineer & AI Researcher",
    department: "Computer Science & Engineering",
    year: "Final Year (4th Year)",
    bio: "Passionate about React, Next.js, and Generative AI. Love helping peers level up their frontend architectures and build scalable apps.",
    coins: 60,
    xp: 450,
    streak: 12,
    rating: 4.95,
    totalReviews: 28,
    completedHours: 32,
    badges: ["Master Mentor", "Fast Responder", "AI Pioneer", "Top Contributor"],
    skillsOffered: ["React & Next.js", "TypeScript", "AI Agent Pipelines", "Tailwind CSS"],
    skillsWanted: ["UI/UX Design", "Figma Prototyping", "Public Speaking"],
    availability: ["Mon 4-7 PM", "Wed 5-8 PM", "Sat 10 AM-2 PM"],
    location: "Tech Innovation Lab / Virtual",
    connectedUserIds: ["user_2", "user_3"]
  },
  {
    id: "user_2",
    name: "Priya Sharma",
    email: "priya@skillswap.edu",
    passwordHash: DEFAULT_HASH,
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    role: "Lead Product & UI/UX Designer",
    department: "Design & Media Arts",
    year: "3rd Year",
    bio: "Design system enthusiast. Mentored 40+ students in Figma, wireframing, typography, and micro-animations. Always eager to learn backend basics.",
    coins: 75,
    xp: 520,
    streak: 18,
    rating: 4.98,
    totalReviews: 36,
    completedHours: 42,
    badges: ["Design Wizard", "Super Mentor", "Streak Master", "Community Hero"],
    skillsOffered: ["UI/UX Design", "Figma & Prototyping", "Design Systems", "User Research"],
    skillsWanted: ["React & Next.js", "Python Data Science", "Git & GitHub"],
    availability: ["Tue 3-6 PM", "Thu 4-8 PM", "Sun 11 AM-4 PM"],
    location: "Design Studio A / Virtual",
    connectedUserIds: ["user_1", "user_4"]
  },
  {
    id: "user_3",
    name: "Marcus Chen",
    email: "marcus@skillswap.edu",
    passwordHash: DEFAULT_HASH,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    role: "Competitive Programmer & ML Engineer",
    department: "Computer Science",
    year: "3rd Year",
    bio: "ICPC Regional Finalist. Specialized in Data Structures, Dynamic Programming, Graphs, and PyTorch deep learning models.",
    coins: 40,
    xp: 380,
    streak: 9,
    rating: 4.9,
    totalReviews: 22,
    completedHours: 26,
    badges: ["Algorithm Ace", "Problem Solver", "Data Guru"],
    skillsOffered: ["Data Structures & Algorithms", "C++ / Python", "Machine Learning", "Dynamic Programming"],
    skillsWanted: ["Mobile App Development", "Flutter", "DevOps & Docker"],
    availability: ["Mon 6-9 PM", "Fri 4-8 PM", "Sat 2-6 PM"],
    location: "CS Library Pod 4 / Virtual",
    connectedUserIds: ["user_1", "user_5"]
  },
  {
    id: "user_4",
    name: "Sara Jenkins",
    email: "sara@skillswap.edu",
    passwordHash: DEFAULT_HASH,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    role: "Mobile App Developer & Flutter Specialist",
    department: "Information Technology",
    year: "2nd Year",
    bio: "Built 5+ published iOS & Android apps with Flutter and Firebase. Looking to master cloud deployment and system design.",
    coins: 30,
    xp: 290,
    streak: 7,
    rating: 4.88,
    totalReviews: 17,
    completedHours: 19,
    badges: ["Mobile Maestro", "Rising Star"],
    skillsOffered: ["Flutter & Dart", "Mobile UI", "Firebase Backend", "State Management"],
    skillsWanted: ["Data Structures & Algorithms", "C++", "System Design"],
    availability: ["Wed 2-5 PM", "Thu 6-9 PM", "Sat 1-5 PM"],
    location: "Incubation Hub / Virtual",
    connectedUserIds: ["user_2"]
  },
  {
    id: "user_5",
    name: "Devon Vance",
    email: "devon@skillswap.edu",
    passwordHash: DEFAULT_HASH,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    role: "Cloud Architect & DevOps Enthusiast",
    department: "Information Systems",
    year: "Final Year (4th Year)",
    bio: "Docker, Kubernetes, AWS, and CI/CD pipeline evangelist. Teaching real-world automated testing and serverless deployments.",
    coins: 50,
    xp: 410,
    streak: 11,
    rating: 4.92,
    totalReviews: 24,
    completedHours: 30,
    badges: ["Cloud Champion", "DevOps Prodigy", "Reliability Rock"],
    skillsOffered: ["Docker & Kubernetes", "AWS & Cloud", "CI/CD Pipelines", "Linux & Bash"],
    skillsWanted: ["AI Agent Pipelines", "TypeScript", "UI/UX Design"],
    availability: ["Mon 5-8 PM", "Thu 5-8 PM", "Sun 2-6 PM"],
    location: "Cloud Computing Lab / Virtual",
    connectedUserIds: ["user_3"]
  },
  {
    id: "user_6",
    name: "Ananya Patel",
    email: "ananya@skillswap.edu",
    passwordHash: DEFAULT_HASH,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    role: "Debate Captain & Public Speaker",
    department: "Communication Studies",
    year: "3rd Year",
    bio: "National debate winner and campus TEDx host. Helping engineering and business students craft compelling pitches, body language, and slide decks.",
    coins: 45,
    xp: 340,
    streak: 8,
    rating: 4.96,
    totalReviews: 20,
    completedHours: 24,
    badges: ["Orator Supreme", "Confidence Coach"],
    skillsOffered: ["Public Speaking", "Pitch Deck Presentations", "Interview Prep", "Storytelling"],
    skillsWanted: ["React & Next.js", "Web Development", "Python Basics"],
    availability: ["Tue 4-7 PM", "Fri 3-6 PM", "Sun 10 AM-1 PM"],
    location: "Student Center Lounge / Virtual",
    connectedUserIds: []
  }
];

export const INITIAL_CONNECTION_REQUESTS = [
  {
    id: "req_101",
    fromUserId: "user_6",
    fromUserName: "Ananya Patel",
    fromUserAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    fromUserRole: "Debate Captain & Public Speaker",
    toUserId: "user_1",
    note: "Hey Alex! I saw your React and AI projects. I'd love to connect and exchange public speaking/pitching tips for frontend web guidance!",
    status: "PENDING",
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString()
  },
  {
    id: "req_102",
    fromUserId: "user_4",
    fromUserName: "Sara Jenkins",
    fromUserAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    fromUserRole: "Mobile App Developer & Flutter Specialist",
    toUserId: "user_1",
    note: "Hi Alex! I'm building a Flutter cross-platform client and would love to exchange ideas on REST API architecture.",
    status: "PENDING",
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString()
  }
];

export const INITIAL_SKILLS = [
  {
    id: "skill_1",
    userId: "user_1",
    userName: "Alex Rivera",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    userRating: 4.95,
    title: "Modern React 19 & Next.js App Router Masterclass",
    category: "Web Development",
    description: "Learn server components, client interactivity, streaming SSR, API routes, custom hooks, and Tailwind CSS design patterns from scratch.",
    level: "Intermediate",
    tags: ["React", "Next.js", "JavaScript", "Frontend"],
    hourlyCostCoins: 10,
    studentsTaught: 24,
    rating: 4.96,
  },
  {
    id: "skill_2",
    userId: "user_2",
    userName: "Priya Sharma",
    userAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    userRating: 4.98,
    title: "Figma UI/UX Design System & Interactive Prototyping",
    category: "Design & Creative",
    description: "Master modern Figma auto-layout, variables, dark mode color tokens, micro-interactions, wireframing, and interactive developer handoffs.",
    level: "All Levels",
    tags: ["Figma", "UI/UX", "Design Systems", "Prototyping"],
    hourlyCostCoins: 10,
    studentsTaught: 38,
    rating: 4.99,
  },
  {
    id: "skill_3",
    userId: "user_3",
    userName: "Marcus Chen",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    userRating: 4.9,
    title: "Data Structures, Algorithms & LeetCode Problem Solving",
    category: "Computer Science",
    description: "Conquer tech interviews with systematic tree traversals, graph algorithms (BFS/DFS, Dijkstra), 2D Dynamic Programming, and time complexity analysis.",
    level: "Advanced",
    tags: ["DSA", "LeetCode", "C++", "Python", "Interviews"],
    hourlyCostCoins: 10,
    studentsTaught: 22,
    rating: 4.91,
  },
  {
    id: "skill_4",
    userId: "user_4",
    userName: "Sara Jenkins",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    userRating: 4.88,
    title: "Cross-Platform Mobile App Development with Flutter",
    category: "Mobile Development",
    description: "Build iOS and Android applications with clean state management (Riverpod/Bloc), smooth 60fps animations, Firebase auth, and camera integration.",
    level: "Beginner to Intermediate",
    tags: ["Flutter", "Dart", "iOS", "Android", "Mobile"],
    hourlyCostCoins: 10,
    studentsTaught: 19,
    rating: 4.89,
  },
  {
    id: "skill_5",
    userId: "user_5",
    userName: "Devon Vance",
    userAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    userRating: 4.92,
    title: "Docker, Kubernetes & Automated CI/CD Cloud Pipelines",
    category: "DevOps & Cloud",
    description: "Containerize web services, manage multi-container Docker Compose stacks, set up GitHub Actions CI/CD workflows, and deploy live on cloud servers.",
    level: "Intermediate",
    tags: ["Docker", "Kubernetes", "DevOps", "AWS", "CI/CD"],
    hourlyCostCoins: 10,
    studentsTaught: 27,
    rating: 4.93,
  },
  {
    id: "skill_6",
    userId: "user_6",
    userName: "Ananya Patel",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    userRating: 4.96,
    title: "High-Impact Public Speaking & Pitch Deck Delivery",
    category: "Personal Development",
    description: "Eliminate public speaking anxiety, master voice modulation and pacing, structure 3-minute hackathon pitches, and capture any audience's attention.",
    level: "All Levels",
    tags: ["Public Speaking", "Pitching", "Communication", "Leadership"],
    hourlyCostCoins: 10,
    studentsTaught: 21,
    rating: 4.97,
  }
];

export const INITIAL_SESSIONS = [
  {
    id: "sess_101",
    mentorId: "user_1",
    mentorName: "Alex Rivera",
    mentorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    learnerId: "user_2",
    learnerName: "Priya Sharma",
    learnerAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    skillTitle: "React Server Components & Next.js 15 Deep Dive",
    category: "Web Development",
    scheduledAt: new Date(Date.now() + 3600000 * 2).toISOString(),
    durationMinutes: 60,
    type: "VIRTUAL",
    status: "CONFIRMED",
    coinsEscrow: 10,
    otpCode: "4892",
    qrToken: "SKILLSWAP-SESS-101-SECURE-KEY",
    meetingRoomId: "room-react-nextjs-101",
    notes: "Review async server components, cache revalidation, and build a real-time data table.",
  },
  {
    id: "sess_102",
    mentorId: "user_2",
    mentorName: "Priya Sharma",
    mentorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    learnerId: "user_3",
    learnerName: "Marcus Chen",
    learnerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    skillTitle: "Figma Component Variables & Dark Mode Systems",
    category: "Design & Creative",
    scheduledAt: new Date(Date.now() + 3600000 * 24).toISOString(),
    durationMinutes: 60,
    type: "IN_PERSON",
    status: "CONFIRMED",
    coinsEscrow: 10,
    otpCode: "7134",
    qrToken: "SKILLSWAP-SESS-102-SECURE-KEY",
    meetingRoomId: "room-figma-102",
    notes: "Meeting at Campus Innovation Lab Pod 2. Bring laptop with Figma desktop app installed.",
  },
  {
    id: "sess_100",
    mentorId: "user_3",
    mentorName: "Marcus Chen",
    mentorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    learnerId: "user_1",
    learnerName: "Alex Rivera",
    learnerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    skillTitle: "Dynamic Programming on Trees & DAGs",
    category: "Computer Science",
    scheduledAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    durationMinutes: 60,
    type: "VIRTUAL",
    status: "COMPLETED",
    coinsEscrow: 10,
    otpCode: "9210",
    qrToken: "SKILLSWAP-SESS-100-SECURE-KEY",
    meetingRoomId: "room-dp-100",
    notes: "Covered subtree memoization and topological sort.",
  }
];

export const INITIAL_TRANSACTIONS = [
  {
    id: "tx_1",
    userId: "user_1",
    amount: 50,
    type: "BONUS",
    description: "Welcome grant for joining SkillSwap campus community",
    date: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "tx_2",
    userId: "user_1",
    amount: 10,
    type: "EARNED",
    description: "Taught 'React Server Components' to Priya Sharma",
    date: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "tx_3",
    userId: "user_1",
    amount: -10,
    type: "SPENT",
    description: "Learned 'Dynamic Programming' from Marcus Chen",
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "tx_4",
    userId: "user_1",
    amount: 10,
    type: "EARNED",
    description: "Taught 'Tailwind CSS Design Systems' to Devon Vance",
    date: new Date(Date.now() - 86400000 * 1).toISOString(),
  }
];

export const INITIAL_REVIEWS = [
  {
    id: "rev_1",
    sessionId: "sess_100",
    mentorId: "user_3",
    mentorName: "Marcus Chen",
    learnerId: "user_1",
    learnerName: "Alex Rivera",
    learnerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Marcus is an exceptional mentor! He explained tree dynamic programming with crystal clear visual diagrams and helped me solve 3 tricky LeetCode hard problems in under an hour.",
    badges: ["Crystal Clear Explanations", "Patient & Thorough", "Code Master"],
    createdAt: new Date(Date.now() - 3600000 * 46).toISOString(),
  },
  {
    id: "rev_2",
    sessionId: "sess_99",
    mentorId: "user_1",
    mentorName: "Alex Rivera",
    learnerId: "user_2",
    learnerName: "Priya Sharma",
    learnerAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Alex made React 19 concepts so approachable! The live coding session was interactive and we fixed a complex state bug together seamlessly.",
    badges: ["Hands-on Expert", "Friendly Mentor"],
    createdAt: new Date(Date.now() - 3600000 * 70).toISOString(),
  }
];

export const INITIAL_ROADMAPS = [
  {
    id: "road_1",
    userId: "user_1",
    goalSkill: "Full-Stack AI Application Development",
    targetWeeks: 4,
    weeklyHours: 6,
    progress: 45,
    steps: [
      {
        week: 1,
        title: "LLM APIs & Prompt Engineering Fundamentals",
        description: "Master OpenAI/Anthropic/Gemini SDKs, streaming responses, and structured JSON outputs.",
        status: "COMPLETED",
        resources: ["DeepLearning.AI Prompt Course", "Next.js AI SDK Documentation"],
        tasks: [
          "Set up streaming chat API route",
          "Implement structured output schemas with Zod",
          "Build interactive message token counter"
        ]
      },
      {
        week: 2,
        title: "Vector Embeddings & RAG Knowledge Retrieval",
        description: "Generate chunked vector embeddings and perform cosine similarity search with Pinecone/Qdrant.",
        status: "IN_PROGRESS",
        resources: ["LangChain RAG Handbook", "Vector Math Fundamentals"],
        tasks: [
          "Extract and chunk markdown documents",
          "Create in-memory vector similarity index",
          "Connect conversational chat with contextual search"
        ]
      },
      {
        week: 3,
        title: "Autonomous Tool-Calling Agents & Function Execution",
        description: "Build multi-step agent loops capable of reading database records, searching web APIs, and computing code.",
        status: "PENDING",
        resources: ["Agent Architecture Patterns", "Function Calling Specs"],
        tasks: [
          "Define agent tool schema declarations",
          "Implement recursive tool dispatch loop",
          "Add user approval interrupt checkpoints"
        ]
      },
      {
        week: 4,
        title: "Full-Stack Deployment & Production Observability",
        description: "Deploy to serverless edge functions with telemetry logging, rate limiting, and cost controls.",
        status: "PENDING",
        resources: ["Vercel Edge Runtime Guide", "OpenTelemetry Tracing"],
        tasks: [
          "Configure Redis token rate limiter",
          "Add structured latency and token usage metrics",
          "Deploy live production instance"
        ]
      }
    ],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString()
  }
];
